//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_don_hang
    {
        public int ma_ct { get; set; }
        public int ma_don { get; set; }
        public int ma_thuoc { get; set; }
        public int so_luong { get; set; }
        public decimal don_gia { get; set; }
    
        public virtual don_hang don_hang { get; set; }
        public virtual thuoc thuoc { get; set; }
    }
}
