//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tai_khoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tai_khoan()
        {
            this.khach_hang = new HashSet<khach_hang>();
        }
    
        public int ma_tai_khoan { get; set; }
        public string ten_dang_nhap { get; set; }
        public string mat_khau { get; set; }
        public string vai_tro { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<khach_hang> khach_hang { get; set; }
    }
}
