//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public thuoc()
        {
            this.chi_tiet_don_hang = new HashSet<chi_tiet_don_hang>();
        }
    
        public int ma_thuoc { get; set; }
        public string ten_thuoc { get; set; }
        public int ma_loai { get; set; }
        public decimal don_gia { get; set; }
        public Nullable<int> so_luong { get; set; }
        public string mo_ta { get; set; }
        public string hinh_anh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_don_hang> chi_tiet_don_hang { get; set; }
        public virtual loai_thuoc loai_thuoc { get; set; }
    }
}
